### ISSUE TITLE
Buffer based

### ISSUE THREAD

**Issue by robnorr** [afms135/signl#32]
Tried to send audio buffers straight from jack to each plugin as it's the more normal way of operating when doing audio stuff. But mainly tried it to halve the latency of the convolution plugin.

Tried on a new branch here bd3dcbe66a859814dcbf2434dfa134225c111fe3

And while it compiles and runs - can even see that audio is going through properly - the line out is silent. No idea why.

**Comment by afms135** [comment]
This doesn't work because the `*out` pointer that jack gives us is a buffer that you need to _write_ into.
So swapping the pointers like in the null plugin won't work. Basically the operator signiture would need to be changed to `void operator()(float *in, float *out, unsigned int frames)` and the jack->signl callback
would need to be changed to `virtual void process(sample_t* in, sample_t *out, jack_nframes_t frames) = 0;`

**Comment by robnorr** [comment]
That makes sense. I've decided it's fine to leave it as it is (non-buffer based), because it gives more flexibility to those plugins that do need buffers (i.e. convolution) over the buffer size etc. At the cost of double latency, but that's okay for now, and probably will be forever (I hope)

**Comment by afms135** [comment]
Should we close this? It can always be reopened if necessary.
